### ISSUE TITLE
Font size improvement on Play screen

### ISSUE THREAD

**Issue by archanajjoshi** [mcgillij/AQ#3]
Just increase the font size. The words are hard to read, or use a seperate font

![image](https://github.com/user-attachments/assets/448219e1-f2fc-48f8-8dba-fd9e7f08bb57)

**Comment by mcgillij** [comment]
Yeah this whole page is basically just a placeholder (and just central place) till I can make a UI elements for them to be accessible from the other screens. But I can def bump up the font size here easily for the time being.

**Comment by mcgillij** [comment]
![image](https://github.com/user-attachments/assets/076ea7c5-aec8-42fe-9c2d-31d1b7a31bec)
